-- This module serves as the root of the `OrdinalsInductionRecursion` library.
-- Import modules here that should be built as part of the library.
import OrdinalsInductionRecursion.TarskiOrd.UCode
import OrdinalsInductionRecursion.TarskiOrd.Universes
import OrdinalsInductionRecursion.TarskiOrd.PreOrd
import OrdinalsInductionRecursion.TarskiOrd.Cardinals
import OrdinalsInductionRecursion.TarskiOrd.Ordinals
import OrdinalsInductionRecursion.TarskiOrd.Transfinite
import OrdinalsInductionRecursion.TarskiOrd.Cofinality
import OrdinalsInductionRecursion.TarskiOrd.Embeddings

import OrdinalsInductionRecursion.TarskiSet.Tree
import OrdinalsInductionRecursion.TarskiSet.Axioms
import OrdinalsInductionRecursion.TarskiSet.Embeddings
import OrdinalsInductionRecursion.TarskiSet.EmbedDybjer

import OrdinalsInductionRecursion.TarskiOrd.El
import OrdinalsInductionRecursion.TarskiOrd.Alephs
import OrdinalsInductionRecursion.TarskiOrd.Mostowski
import OrdinalsInductionRecursion.TarskiOrd.CardinalsOrder
import OrdinalsInductionRecursion.TarskiOrd.Arith
import OrdinalsInductionRecursion.TarskiOrd.Order
import OrdinalsInductionRecursion.TarskiOrd.Lattice
import OrdinalsInductionRecursion.TarskiOrd.Cofinality
import OrdinalsInductionRecursion.TarskiOrd.CardinalsFamily
import OrdinalsInductionRecursion.DybjerOrd.Univ
import OrdinalsInductionRecursion.DybjerOrd.PreOrd
import OrdinalsInductionRecursion.DybjerOrd.Ordinals
import OrdinalsInductionRecursion.DybjerOrd.Order
import OrdinalsInductionRecursion.DybjerOrd.Lattice
import OrdinalsInductionRecursion.DybjerOrd.Arith
import OrdinalsInductionRecursion.DybjerOrd.Cardinals
import OrdinalsInductionRecursion.DybjerOrd.Mostowski
import OrdinalsInductionRecursion.DybjerOrd.Transfinite
import OrdinalsInductionRecursion.DybjerOrd.Universes
import OrdinalsInductionRecursion.DybjerOrd.Alephs
import OrdinalsInductionRecursion.DybjerOrd.CardinalsOrder
import OrdinalsInductionRecursion.DybjerOrd.Cofinality
import OrdinalsInductionRecursion.DybjerOrd.CardinalsFamily
import OrdinalsInductionRecursion.DybjerOrd.Beth
import OrdinalsInductionRecursion.DybjerOrd.Inaccessible

import OrdinalsInductionRecursion.CountableSets.HCSet
import OrdinalsInductionRecursion.UnivSets.Axioms
import OrdinalsInductionRecursion.TarskiSet.Axioms
import OrdinalsInductionRecursion.DybjerSet.Axioms
import OrdinalsInductionRecursion.UnivSets.Lift
import OrdinalsInductionRecursion.UnivOrd.Ordinals
import OrdinalsInductionRecursion.UnivOrd.WellOrder
import OrdinalsInductionRecursion.UnivOrd.OrdinalsLattice
import OrdinalsInductionRecursion.UnivSets.Embeddings
import OrdinalsInductionRecursion.UnivSets.EmbedDybjer
import OrdinalsInductionRecursion.UnivOrd.Arith
import OrdinalsInductionRecursion.UnivOrd.Isomorphism
import OrdinalsInductionRecursion.UnivOrd.Cardinals
import OrdinalsInductionRecursion.UnivOrd.Induction
import OrdinalsInductionRecursion.LargeCardinals.Inaccessible
import OrdinalsInductionRecursion.LargeCardinals.Filters
import OrdinalsInductionRecursion.LargeCardinals.CUB
import OrdinalsInductionRecursion.LargeCardinals.Mahlo
import OrdinalsInductionRecursion.LargeCardinals.Measurable
import OrdinalsInductionRecursion.LargeCardinals.Supercompact
import OrdinalsInductionRecursion.LargeCardinals.Vopenka
import OrdinalsInductionRecursion.UnivOrd.Lift
import OrdinalsInductionRecursion.CountableOrd.Induction
import OrdinalsInductionRecursion.ModelTheory.Universe
import OrdinalsInductionRecursion.ModelTheory.Structures
import OrdinalsInductionRecursion.ModelTheory.Embeddings

-- MK⁺ (TG+VP) Foundation
import OrdinalsInductionRecursion.MKplusCAC.Prelim
import OrdinalsInductionRecursion.MKplusCAC.MKplusCACAxioms
import OrdinalsInductionRecursion.MKplusCAC.Relations
import OrdinalsInductionRecursion.MKplusCAC.Functions
import OrdinalsInductionRecursion.MKplusCAC.Tarski
import OrdinalsInductionRecursion.MKplusCAC.Vopenka
