-- This module serves as the root of the `OrdinalsInductionRecursion` library.
-- Import modules here that should be built as part of the library.
import OrdinalsInductionRecursion.TarskiOrd.UCode
import OrdinalsInductionRecursion.TarskiOrd.Universes
import OrdinalsInductionRecursion.TarskiOrd.PreOrd
import OrdinalsInductionRecursion.TarskiOrd.Cardinals
import OrdinalsInductionRecursion.TarskiOrd.Ordinals
import OrdinalsInductionRecursion.TarskiOrd.Transfinite
import OrdinalsInductionRecursion.TarskiOrd.Arith
import OrdinalsInductionRecursion.TarskiOrd.Order
import OrdinalsInductionRecursion.TarskiOrd.Lattice
import OrdinalsInductionRecursion.TarskiOrd.El
import OrdinalsInductionRecursion.TarskiOrd.Alephs
import OrdinalsInductionRecursion.DybjerOrd.Univ
import OrdinalsInductionRecursion.DybjerOrd.PreOrd
import OrdinalsInductionRecursion.DybjerOrd.Ordinals
import OrdinalsInductionRecursion.DybjerOrd.Order
import OrdinalsInductionRecursion.DybjerOrd.Lattice
import OrdinalsInductionRecursion.DybjerOrd.Arith
import OrdinalsInductionRecursion.DybjerOrd.Cardinals
import OrdinalsInductionRecursion.DybjerOrd.Mostowski
import OrdinalsInductionRecursion.DybjerOrd.Transfinite
import OrdinalsInductionRecursion.DybjerOrd.Universes
import OrdinalsInductionRecursion.DybjerOrd.Alephs

import OrdinalsInductionRecursion.CountableSets.HCSet
import OrdinalsInductionRecursion.UnivSets.Axioms
import OrdinalsInductionRecursion.UnivSets.Lift
import OrdinalsInductionRecursion.UnivOrd.Ordinals
import OrdinalsInductionRecursion.UnivOrd.WellOrder
import OrdinalsInductionRecursion.UnivOrd.OrdinalsLattice
import OrdinalsInductionRecursion.UnivOrd.Arith
import OrdinalsInductionRecursion.UnivOrd.Isomorphism
import OrdinalsInductionRecursion.UnivOrd.Cardinals
import OrdinalsInductionRecursion.UnivOrd.Induction
import OrdinalsInductionRecursion.UnivOrd.Inaccessible
import OrdinalsInductionRecursion.UnivOrd.Lift
import OrdinalsInductionRecursion.CountableOrd.Induction
